spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blockix
    username: postgres
    password: 1954623790
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: '{"kty": "oct", "k": "kL9yZ1mB5aV4bU9qH4mO0wN5hT3cL6gP2xV1cU5wA7oH9xV7qW8oA6hG5bU4l"}'
  token-expiration: '15m'
